# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'newsforall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for newsforall
  pod 'Alamofire'
  pod 'PINRemoteImage'
  pod 'IHProgressHUD'
  pod 'NotificationBannerSwift', '~> 3.0.0'
  pod 'ReachabilitySwift'

end
